name: history_hub_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_image_compress: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.1.1
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gap: ^3.0.1
  flutter_slider_drawer: ^2.1.3
  flutter_svg: ^2.0.10+1

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - .env
  - assets/icons/
  - assets/images/
  - assets/logos/

