name: history_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  image_picker: ^1.1.0
  image_sketcher: ^0.0.4
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/logos/
